services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  GeorgRinger\Doc\:
    resource: '../Classes/* '

  dashboard.widget.gotoProjectDocumentation:
    class: 'TYPO3\CMS\Dashboard\Widgets\CtaWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $buttonProvider: '@GeorgRinger\Doc\Widgets\Provider\ExtDocButtonProvider'
      $options:
        text: 'LLL:EXT:doc/Resources/Private/Language/locallang.xlf:widget.text'
    tags:
      - name: dashboard.widget
        identifier: 'gotoProjectDocumentation'
        groupNames: 'documentation'
        title: 'LLL:EXT:doc/Resources/Private/Language/locallang.xlf:widget.title'
        description: 'LLL:EXT:doc/Resources/Private/Language/locallang.xlf:widget.description'
        iconIdentifier: 'content-widget-text'
        height: 'small'

  GeorgRinger\Doc\Widgets\Provider\ExtDocButtonProvider:
    arguments:
      $title: 'LLL:EXT:doc/Resources/Private/Language/locallang.xlf:widget.buttonText'
